### ISSUE TITLE
Lunch is broken

### ISSUE THREAD

**Issue by Levis92** [cthit/chalmersit-lunch#3]
![3a951413-eba3-454a-a09f-ec754632d27b](https://user-images.githubusercontent.com/16805105/47232423-f52f2a00-d3cf-11e8-834c-3fc3a220d245.png)

**Comment by Portals** [comment]
This was due to an issue on our servers. This has since been resolved. The crash had nothing to do with chalmersit-lunch.

**Comment by Levis92** [comment]
Yeah, thought so. Was just easier to add the issue here 😜
